# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /Users/build/conda-recipes/dssp, last modified Mon Feb  3 10:20:55 2020
# ------------------------------------------------

package:
    name: dssp
    version: 3.0.0
source:
    fn: dssp-3.0.0.tgz
    patches:
        - dssp-boost-tr1.patch
    sha256: 25d39a2107767b622a59dd9fa790112c1516564b8518fc6ac0fab081d5ac3ab0
    url: ftp://ftp.cmbi.ru.nl/pub/software/dssp/dssp-3.0.0.tgz
build:
    number: '3'
    string: h0a44026_3
requirements:
    build:
        - blas 1.0 mkl
        - boost 1.67.0 py37_4
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.1.1 0
        - cctools 895 1
        - certifi 2019.11.28 py37_0
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - icu 58.2 h4b95b61_1
        - intel-openmp 2019.4 233
        - ld64 274.2 1
        - libboost 1.67.0 hebc422b_4
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - libiconv 1.15 hdd342a3_7
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - mkl 2019.4 233
        - mkl-service 2.3.0 py37hfbe908c_0
        - mkl_fft 1.0.15 py37h5e564d8_0
        - mkl_random 1.1.0 py37ha771720_0
        - ncurses 6.1 h0a44026_1
        - numpy 1.18.1 py37h7241aed_0
        - numpy-base 1.18.1 py37h6575580_1
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py37_1
        - py-boost 1.67.0 py37h6440ff4_4
        - python 3.7.6 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py37_0
        - six 1.14.0 py37_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
    run:
        - bzip2 1.0.8.*
        - libboost 1.67.0.*
        - libcxx >=4.0.1
        - zlib 1.2.11.*
test:
    commands:
        - mkdssp --version
about:
    description: 'The DSSP program was designed by Wolfgang Kabsch and Chris Sander
        to standardize secondary structure assignment. DSSP is a database of secondary
        structure assignments (and much more) for all protein entries in the Protein
        Data Bank (PDB). DSSP is also the program that calculates DSSP entries from
        PDB entries. DSSP does not predict secondary structure.

        See [the DSSP website](http://swift.cmbi.ru.nl/gv/dssp/) for more details.

        If you have problems with this conda package, please [open an issue](https://github.com/salilab/conda-recipes/issues).

        '
    home: http://swift.cmbi.ru.nl/gv/dssp/
    license: Boost
    summary: Secondary structure assignment
extra:
    copy_test_source_files: true
    final: true
